version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/node:14.19
    steps:
      - checkout
      - run:
          name: install_npm
          command: sudo npm install -g npm
      - run:
          name: npm_install_packages
          command: npm install
      - run:
          name: run_tests
          command: npm run test

